### PR TITLE
remove unnecessary conversion

### LINKED ISSUE #1131: `system networking addr add` returns `NoPrefix` error
### Component

- [x] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

Per @internet-diglett, the line in error is not needed anymore. GW is an IpAddr now (because that's what the user provides when they create this resource), so turning it into a string, parsing it as an IpNet, the getting the addr of the IpNet isn't correct. It should be parsed and used as an IpAddr now.

### What is the current behaviour and what actions did you take to get there

I was trying out some bgp switch port settings change on berlin (following the BGP guide to add bgp to an existing static route setup). I got this error when attempting this step:
```
$ oxide --profile recovery system networking addr add --rack $rack --switch switch0        --port qsfp0 --addr 172.20.15.69/29 --lot peering
thread 'main' panicked at cli/src/cmd_net.rs:1785:65:
called `Result::unwrap()` on an `Err` value: NoPrefix
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The line it complained about https://github.com/oxidecomputer/oxide.rs/blob/main/cli/src/cmd_net.rs#L1785 seems to be about static route

### CLI or SDK version

Built from commit: eefa2e3c5f670e8d26ffdbd03b7e44ed16882cf8

### Operating system

jammy

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by internet-diglett**
Related
---
Resolves #1131

### CODE REVIEW

File: cli/src/cmd_net.rs [hunk 1]
```diff
@@ -1781,14 +1781,11 @@ async fn create_current(settings_id: Uuid, client: &Client) -> Result<SwitchPort
...
-                    dst: x.dst.clone(),
-                    gw: gw.addr(),
-                    vid: x.vlan_id,
-                    rib_priority: x.rib_priority,
-                }
+            .map(|x| Route {
+                dst: x.dst.clone(),
+                gw: x.gw,
+                vid: x.vlan_id,
+                rib_priority: x.rib_priority,
```
Comment (ahl) [inline cli/src/cmd_net.rs]: Consider deleting `iter()` and

```suggestion
            .into_iter()
            .map(
                |SwitchPortRouteConfig {
                     dst,
                     gw,
                     rib_priority,
                     vlan_id,
                     ..
                 }| Route {
                    dst,
                    gw,
                    vid: vlan_id,
                    rib_priority,
                },
            )
```

Or maybe just `into_iter` and delete the `clone`

You might take a look at API consistency: why is it `vid` vs. `vlan_id`?

**Review by ahl — APPROVED** [review]
Do you want to add a test?
