### PR TITLE
CLI could have more helpful error messages for the Name type

### LINKED ISSUE #458: Better error message/checking for `Name`
Seeing an error of `doesn't match pattern "^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z][a-z0-9-]*[a-zA-Z0-9]*$"` technically tells me what is wrong but I hate debugging regexes. Arguably, the description from openapi is actually more useful

```
      "Name": {
        "title": "A name unique within the parent collection",
        "description": "Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID though they may contain a UUID.",
        "type": "string",
        "pattern": "^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z][a-z0-9-]*[a-zA-Z0-9]*$",
        "minLength": 1,
        "maxLength": 63
      },
```

### PR DESCRIPTION
**Pull request by ahl**
Fixes #458

### CODE REVIEW

File: sdk/src/clap_feature.rs [hunk 1]
```diff
@@ -132,31 +132,87 @@ impl clap::builder::TypedValueParser for NameOrIdParser {
...
+        &self,
+        cmd: &clap::Command,
+        arg: Option<&clap::Arg>,
+        value: &std::ffi::OsStr,
+    ) -> Result<Self::Value, clap::Error> {
+        fn parse(value: &str) -> Result<types::Name, String> {
+            types::Name::from_str(value)
+                .map_err(|e| {
+                    if value.len() > 63 {
+                        return "names must be at most 63-characters in length";
```
Comment (david-crespo) [inline sdk/src/clap_feature.rs]: 🙅 to that dash
