### PR TITLE
Handle empty credentials.toml files

### LINKED ISSUE #797: cannot perform other auth commands after `oxide auth logout -a`
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

I used the Oxide CLI to log out of all sessions, but due to the resulting state of the files in `~/.config/oxide`, it unexpectedly no longer allowed me to perform authentication-related actions.

### What is the current behaviour and what actions did you take to get there

- I was already logged in via `oxide auth login --host <url> --no-browser`, sometimes to multiple profiles.
- l logged out of everything via `oxide auth logout -a`
- Note this last command causes `~/.config/oxide/credentials.toml` to become empty, and `~/.config/oxide/config.toml ` unchanged (which means that `default-profile` now refers to a profile that doesn't exist).
- I can no longer perform further auth commands. Examples of commands that don't work:

```
% oxide auth status
TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `profile`
``` 

```
% oxide auth login --host <url> --no-browser
TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `profile`
```

- I got around this problem by removing the `~/.config/oxide` directory (by changing the directory name to another name), so that it would start over from scratch.

### CLI or SDK version

0.6.2+20240710.0

### Operating system

macOS 14.5

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by wfchandler**
After logging out of all profiles we write an empty `credentials.toml` file to the user's config directory. However, when loading that file we will fail to parse the contents as a TOML table.

Only parse `credentials.toml` if it is not empty, falling back on the default value otherwise.

Closes https://github.com/oxidecomputer/oxide.rs/issues/797

### CODE REVIEW

File: cli/src/context.rs [hunk 1]
```diff
@@ -29,7 +29,14 @@ pub struct ConfigFile {
...
     match std::fs::read_to_string(path) {
-        Ok(contents) => Ok(toml::from_str(&contents)?),
+        Ok(contents) => {
+            // Empty `credentials.toml` files cannot be parsed.
+            if contents.trim().is_empty() {
+                Ok(T::default())
+            } else {
+                Ok(toml::from_str(&contents)?)
+            }
+        }
```
Comment (ahl) [inline cli/src/context.rs]: I'd be more inclined to do this:

```rust
pub struct CredentialsFile {
    #[serde(default)]
    pub profile: BTreeMap<String, ProfileCredentials>,
}
```

What do you think?

Comment (wfchandler) [reply cli/src/context.rs]: That's much cleaner, thanks! Added in 5f83cc0

File: sdk/src/auth.rs [hunk 2]
```diff
@@ -130,6 +130,7 @@ impl ClientConfig {
 }
 
 #[derive(Deserialize, Debug, Default)]
+#[serde(default)]
```
Comment (ahl) [inline sdk/src/auth.rs:133]: I've never seen this in the whole struct, only on fields. TIL!

**Review by ahl — APPROVED** [review]
