### PR TITLE
Add tests for SDK extras and fix `execute`

### LINKED ISSUE #930: disk_import().execute() fails with Error: Disk import canceled
### Component

- [ ] CLI
- [x] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

`disk_import().execute()` should import a disk

### What is the current behaviour and what actions did you take to get there

`disk_import().execute()` seems to immediately cancel the disk upload. I think this is because, since the `handle` is not returned, it is dropped, which the uploader interprets as a cancellation.

Using `disk_import().execute_with_control()` and holding the reference to the `handle` until the upload is done works as expected.

Good:

```rust
let (upload, _handle) = client
    .disk_import()
    .project("project")
    .description(desc)
    .upload_thread_ct(8)
    .disk(name.clone())
    .disk_info(disk_info.clone())
    .execute_with_control()?;

upload.await?;
```

Bad:

```rust
let upload = client
    .disk_import()
    .project("project")
    .description(desc)
    .upload_thread_ct(8)
    .disk(name.clone())
    .disk_info(disk_info.clone())
    .execute()?;

// Returns "Error: Disk import canceled"
upload.await?;
```

### CLI or SDK version

eae1dbdf558aecf8aceb826af5144e251cf26544

### Operating system

Linux

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by wfchandler**
We've been relying on the CLI disk import tests to cover the `extras` disk importer in the SDK. However, the CLI does not use the `execute` method, and we missed that this was failing immediately due to the cancellation sender being dropped before the request could awaited.
      
Add tests for `extras` to validate that both options work. Also, add a method to DiskImport that does not accept cancellation and use that in `execute`.

Closes #930

### CODE REVIEW

File: sdk/src/extras/disk.rs [hunk 1]
```diff
@@ -107,7 +108,12 @@ pub mod builder {
             impl Future<Output = Result<(), DiskImportError>> + 'a,
             Error<crate::types::Error>,
         > {
-            Ok(self.execute_with_control()?.0)
+            let (fut, handle) = self.execute_with_control()?;
+
+            // Leak the handle so we don't cancel the request by dropping it.
+            mem::forget(handle);
```
Comment (ahl) [inline sdk/src/extras/disk.rs]: this seems a bit inelegant. Did we consider other options such as a `run_without_cancel` function, ignoring cancelation from `cancel_rx` in `run_with_cancel` or returning a new `Future` here that holds onto the handle so that it isn't dropped.

**Comment by ahl** [comment]
Also: worth adding a test here?

File: sdk/src/extras/disk.rs (hunk 1 above)
Comment (wfchandler) [reply sdk/src/extras/disk.rs]: That's fair, I've added a `run` method that doesn't take a cancel channel.

**Comment by wfchandler** [comment]
> Also: worth adding a test here?

Yes, great point! I've added a high level test for this.

File: sdk/tests/test_extra.rs [hunk 2]
```diff
@@ -0,0 +1,135 @@
+use httpmock::MockServer;
```
Comment (ahl) [inline sdk/tests/test_extra.rs:7]: Add the license and copyright headers?

**Review by ahl — APPROVED** [review]

File: sdk/tests/test_extra.rs (hunk 2 above)
Comment (wfchandler) [reply sdk/tests/test_extra.rs:7]: Good catch, thanks

**Comment by wfchandler** [comment]
Rebased to resolve merge conflict.
